services:
  clamav-volume-init:
    image: alpine:3.22
    container_name: clamav-volume-init
    command: ["sh", "-c", "chmod -R 0777 /var/lib/clamav || true"]
    volumes:
      - clamav-db:/var/lib/clamav
    restart: "no"

  clamav-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_SWAGGER: true
    container_name: clamav-api
    depends_on:
      clamav-volume-init:
        condition: service_completed_successfully
    user: "1001:1001"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MAX_FILE_SIZE_MB: 200
    restart: unless-stopped
    volumes:
      - clamav-db:/var/lib/clamav

volumes:
  clamav-db:
